- name: Base lab configuration
  hosts: lab
  become: true

  tasks:
# Commenting this out until Canonical DDOS is resolved
#    - name: Update apt cache
#      apt:
#        update_cache: yes
#        cache_valid_time: 3600
#      retries: 5
#      delay: 10
#      register: apt_update
#      until: apt_update is succeeded
#
#    - name: Upgrade apt packages
#      apt:
#        upgrade: yes

    - name: Install packages
      apt:
        name:
          - tmux
        state: present
